/*
 * Copyright (C) 2016 - 2026 Spenego Software LLC. All rights reserved.
 *
 * This file is part of Obidos from Spenego Software LLC
 *
 * Obidos is dual-licensed under a commercial license and the GNU
 * Affero General Public License (AGPL) v3.0. For commercial licensing,
 * contact Spenego Software LLC at https://spenego.com/contacts.html.
 *
 * For AGPL licensing terms, see the LICENSE file in the project root
 * or <https://www.gnu.org/licenses/>.
 */

package test.com.spenego.obidos;

import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.spenego.strongpass.StrengthChecker;

//
// Automatically generated. DO NOT EDIT
// Generated by gen_java_unit_tests.rb 2019-09-02 15:41:37 -0400

public class TestStrongPassGenerated {
	private StrengthChecker strengthChecker = null;

	@Before
	public void setUp() throws Exception {
		strengthChecker = new StrengthChecker(true);
	}

	@After
	public void tearDown() throws Exception { /* no implementation */ }

	private void entropyCheck(String pass, double expectedEntropy, boolean expectedStrong) {
		assertEquals(expectedEntropy, strengthChecker.calculateEntropy(pass), 0.0F);
		assertEquals(expectedStrong, strengthChecker.isStrong(pass));
	}

	private void entropyCheck(String pass, double expectedEntropy) {
		entropyCheck(pass, expectedEntropy, false);
	}

	@Test public void testEntropy1()  { entropyCheck("zxcvbnm, Was it a cat I saw?$",		32.0087890625, true); }
	@Test public void testEntropy2()  { entropyCheck("This is a test",						21.375, true); }
	@Test public void testEntropy3()  { entropyCheck("Cabbage broccoli and cauliflower",	38.0625, true); }
	@Test public void testEntropy4()  { entropyCheck("root",			 2); }
	@Test public void testEntropy5()  { entropyCheck("toor",			 7.5); }
	@Test public void testEntropy6()  { entropyCheck("raspberry",		10); }
	@Test public void testEntropy7()  { entropyCheck("dietpi",			11.5); }
	@Test public void testEntropy8()  { entropyCheck("test",			 2); }
	@Test public void testEntropy9()  { entropyCheck("uploader",		10); }
	@Test public void testEntropy10() { entropyCheck("password",		 2); }
	@Test public void testEntropy11() { entropyCheck("admin",			 2); }
	@Test public void testEntropy12() { entropyCheck("administrator",	16.625); }
	@Test public void testEntropy13() { entropyCheck("marketing",		 8); }
	@Test public void testEntropy14() { entropyCheck("12345678",		 2); }
	@Test public void testEntropy15() { entropyCheck("1234",			 2); }
	@Test public void testEntropy16() { entropyCheck("12345",			 2); }
	@Test public void testEntropy17() { entropyCheck("qwerty",			 2); }
	@Test public void testEntropy18() { entropyCheck("webadmin",		 8); }
	@Test public void testEntropy19() { entropyCheck("webmaster",		 2); }
	@Test public void testEntropy20() { entropyCheck("maintaince",		17.5); }
	@Test public void testEntropy21() { entropyCheck("techsupport",		15.5); }
	@Test public void testEntropy22() { entropyCheck("letmein",			 2); }
	@Test public void testEntropy23() { entropyCheck("logon",			 9.5); }
	@Test public void testEntropy24() { entropyCheck("Passw@rd",		10); }
	@Test public void testEntropy25() { entropyCheck("012345678910",	 8); }
}
