# Global logging configuration taken from Predictionator
# Note: currently delegator.log is created in $HOME
# File from deployment_config
##-log4j.logger.src.com.spenego=INFO, DELEGATOR

##-log4j.rootLogger=ERROR, stdout
##-log4j.rootLogger=DEBUG, stdout
## use DEBUG if you want to see log of info
## This file is used by JUnit test routines
##-log4j.debug=TRUE
##-log4j.rootLogger=INFO, stdout, DELEGATOR

##-log4j.logger.com.ibatis=DEBUG
##-log4j.logger.com.ibatis=WARN
#log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=WARN
#log4j.logger.com.ibatis.common.jdbc.ScriptRunner=WARN
#log4j.logger.com.ibatis.SQL Map.engine.impl.SQL MapClientDelegate=WARN
    
# shows SQL of prepared statements
##-log4j.logger.java.sql.Connection=WARN
##-log4j.logger.java.sql.Statement=WARN
# shows parameters inserted into prepared statements
##-log4j.logger.java.sql.PreparedStatement=WARN
# shows query results
##-log4j.logger.java.sql.ResultSet=WARN

# Define all the appenders
##-log4j.appender.console=org.apache.log4j.ConsoleAppender
##-log4j.appender.DELEGATOR=org.apache.log4j.DailyRollingFileAppender
#log4j.appender.DELEGATOR.File=${catalina.base}/logs/delegator.log
#log4j.appender.DELEGATOR.File=${app.root}/delegator.log
#log4j.appender.DELEGATOR.File=${user.home}/delegator.log
##-log4j.appender.DELEGATOR.File=C:/cygwin/home/605481846/gitdev/Delegator/delegator.log
##-log4j.appender.DELEGATOR.Append=true
##-log4j.appender.DELEGATOR.Encoding=UTF-8
# Roll-over the log once per day
##-log4j.appender.DELEGATOR.DatePattern='.'yyyy-MM-dd'.log'
##-log4j.appender.DELEGATOR.layout = org.apache.log4j.PatternLayout
##-log4j.appender.DELEGATOR.layout.ConversionPattern = %d [%t] %-5p %c- %m%n
#################################################################################
# Root logger option
log4j.rootLogger=INFO, file, stdout

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=/tmp/delegator.log
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=10
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
