/*
 * Copyright (C) 2016 - 2026 Spenego Software LLC. All rights reserved.
 *
 * This file is part of Obidos from Spenego Software LLC
 *
 * Obidos is dual-licensed under a commercial license and the GNU
 * Affero General Public License (AGPL) v3.0. For commercial licensing,
 * contact Spenego Software LLC at https://spenego.com/contacts.html.
 *
 * For AGPL licensing terms, see the LICENSE file in the project root
 * or <https://www.gnu.org/licenses/>.
 */

package com.spenego.Obidos.server.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.spenego.Obidos.server.model.PasswordReset;
import com.spenego.Obidos.server.model.PasswordResetExample;

public interface PasswordResetMapper extends Mapper<PasswordReset> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int countByExample(PasswordResetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int deleteByExample(PasswordResetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int insert(PasswordReset r);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int insertSelective(PasswordReset r);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	List<PasswordReset> selectByExample(PasswordResetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	PasswordReset selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int updateByExampleSelective(@Param("r") PasswordReset r, @Param("example") PasswordResetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int updateByExample(@Param("r") PasswordReset r, @Param("example") PasswordResetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int updateByPrimaryKeySelective(PasswordReset r);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table password_reset
	 * @mbg.generated  Thu Oct 05 08:44:09 EDT 2017
	 */
	int updateByPrimaryKey(PasswordReset r);
}
