/*
 * Copyright (C) 2016 - 2026 Spenego Software LLC. All rights reserved.
 *
 * This file is part of Obidos from Spenego Software LLC
 *
 * Obidos is dual-licensed under a commercial license and the GNU
 * Affero General Public License (AGPL) v3.0. For commercial licensing,
 * contact Spenego Software LLC at https://spenego.com/contacts.html.
 *
 * For AGPL licensing terms, see the LICENSE file in the project root
 * or <https://www.gnu.org/licenses/>.
 */

package com.spenego.Obidos.server.operations.impl;

import java.util.Collection;
import java.util.List;
import java.util.function.Consumer;
import java.util.stream.Stream;

import org.springframework.beans.factory.annotation.Autowired;

import com.spenego.Obidos.server.dao.ContainerAssignmentMapper;
import com.spenego.Obidos.server.dao.Mapper;
import com.spenego.Obidos.server.model.ContainerAssignment;
import com.spenego.Obidos.server.model.ContainerAssignmentExample;
import com.spenego.Obidos.server.model.UserGroupCombo;
import com.spenego.Obidos.server.operations.ContainerAssignmentOperations;
import com.spenego.Obidos.server.utils.Logger;
import com.spenego.Obidos.server.utils.LoggerFactory;
import com.spenego.Obidos.shared.OrderBy;
import com.spenego.Obidos.shared.dto.PermissionDTO;
import com.spenego.Obidos.shared.exceptions.NoSuchRecordException;

public final class ContainerAssignmentOperationsImpl extends ObidosOperations<ContainerAssignment> implements ContainerAssignmentOperations {
	private static final Logger	logger = LoggerFactory.getLogger(ContainerAssignmentOperationsImpl.class);

	@Autowired
	private final ContainerAssignmentMapper	mapper = null;

	@Override protected Logger getLogger()						{ return logger; }
	@Override protected Mapper<ContainerAssignment> getMapper()	{ return mapper; }
	@Override protected String getModelName()					{ return "ContainerAssignment"; }

	private static ContainerAssignmentExample assignedContainersExample(final Long containerId, final Collection<Long> userIds) { return new ContainerAssignmentExample(c -> c.andCAContainerIdEqualTo(containerId).andUserIdIn(userIds).andCountGreaterThan(0)); }

	private ContainerAssignmentExample createBaseExample(final String user_id_col, final Collection<Long> preSelectedElements, final List<OrderBy> orderByList, final Consumer<ContainerAssignmentExample.Criteria> consumer, final Consumer<ContainerAssignmentExample.Criteria> preSelectedUserconsumer) {
		final ContainerAssignmentExample example = new ContainerAssignmentExample(generatePreSelectedOrderClause(preSelectedElements, user_id_col, orderByList), 1024);
		consumer.accept(example.createCriteria());

		if (preSelectedElements != null && !preSelectedElements.isEmpty()) {
			final ContainerAssignmentExample.Criteria criteria = example.createCriteria();

			criteria.andIdIn(preSelectedElements);
			if (preSelectedUserconsumer != null) {
				preSelectedUserconsumer.accept(criteria);
			}
			example.or(criteria);
		}
		return example;
	}

	@Override
	public ContainerAssignment get(final Long containerId, final Long userId) {
		final List<ContainerAssignment> list = mapper.selectByExample(new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId).andUserIdEqualTo(userId)));
		if (list == null || list.isEmpty()) {
			throw new NoSuchRecordException("No such container assignment exists.");
		}
		return list.get(0);
	}

	@Override public Stream<ContainerAssignment> getAll(final Long containerId)						{ return mapper.selectByExample(new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId))).stream(); }
	@Override public Collection<ContainerAssignment> getAssignmentsViaGroupId(final Long groupId)	{ return mapper.selectByExample(new ContainerAssignmentExample(c -> c.andContainersSharedWithGroup(groupId))); }
	@Override public Collection<ContainerAssignment> getAllArtifacts()								{ return mapper.selectByExample(new ContainerAssignmentExample(c -> c.andCountEqualTo(0))); }
	@Override public Integer getShareCount(final Long containerId)									{ return mapper.countByExample(new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId))); }
	/**
	 * This method has half of the SQL generated by the andCAComboContainerIdEqualTo method.
	 */
	@Override public Stream<UserGroupCombo> getContainerAssignmentShares(final Long callerId, final Long containerId, final String searchString, final Collection<Long> preSelectedElements, final Integer offset, final Integer count, final List<OrderBy> orderBy) { return mapper.selectContainerSharesByExample(createBaseExample("id", preSelectedElements, getComboTypeOrderByList(orderBy), c -> c.andCAComboContainerIdEqualTo(callerId, containerId, searchString), null), createRowBounds(offset, count)).stream(); }
	@Override public Integer setSharedExplicitly(final Long containerId, final Collection<Long> userIds, final Boolean sharedExplicitly) { return mapper.updateByExampleSelective(new ContainerAssignment(null, sharedExplicitly, null), assignedContainersExample(containerId, userIds)); }
	@Override public Integer getContainerAssignmentShareCount(final Long callerId, final Long containerId, final String searchString, final Collection<Long> preSelectedElements) { return mapper.countContainerSharesByExample(createBaseExample("id", preSelectedElements, null, c -> c.andCAComboContainerIdEqualTo(callerId, containerId, searchString), null)); }

	@Override public Integer incrementShareCount(final Long id)												{ return attemptOp(e -> mapper.incrementByPrimaryKey(id), null); }
	@Override public Integer decrementShareCount(final Long containerId, final Collection<Long> userIds)	{ return attemptOp(mapper::decrementShareCountByExample, () -> assignedContainersExample(containerId, userIds)); }
	@Override public Integer decrementShareCount(final Long containerId, final Long groupId)				{ return attemptOp(mapper::decrementShareCountByGroupExample, () -> new ContainerAssignmentExample(c -> c.andCAContainerIdEqualTo(containerId).andGroupIdEqualTo(groupId).andUserIdInGroup(groupId).andCountGreaterThan(0))); }
	@Override public Integer decrementShareCountsForUserInGroup(final Long userId, final Long groupId)		{ return attemptOp(mapper::decrementShareCountByGroupExample, () -> new ContainerAssignmentExample(c -> c.andUserIdEqualTo(userId).andUserIdInGroup(groupId))); }
	@Override public Integer deleteArtifacts(final Long containerId)										{ return attemptOp(mapper::deleteByExample, () -> new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId).andCountEqualTo(0))); }
	@Override public Integer deleteArtifactsForUser(final Long userId)										{ return attemptOp(mapper::deleteByExample, () -> new ContainerAssignmentExample(c -> c.andUserIdEqualTo(userId).andCountEqualTo(0))); }
	@Override public Integer deleteAllForUser(final Long userId)											{ return attemptOp(mapper::deleteByExample, () -> new ContainerAssignmentExample(c -> c.andUserIdEqualTo(userId))); }
	@Override public Integer resetShareCount(final Long userId, final Long containerId)						{ return attemptOp(mapper::resetCountByExample, () -> new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId))); }

	@Override
	public Void grantPermissions(final Long containerId, final PermissionDTO permission, final Collection<Long> users) {
		mapper.updateByExampleSelective(new ContainerAssignment(permission), new ContainerAssignmentExample(c -> c.andContainerIdEqualTo(containerId).andUserIdIn(users)));
		return null;
	}

}
