project.version=${project.version}
build.number=${buildNumber}
build.time=${timestamp}
built.by=${user.name}
built.with.java.version=${java.version}
built.with.java.vendor=${java.vendor}
built.on.os.name=${os.name}
built.on.os.arch=${os.arch}
built.on.os.version=${os.version}
